export interface Translation {
  title: string;
  relatedPromo: string;
  subtitle: string;
  copyright: string;
  viewInGallery: string;
  browseGallery: string;
  galleryFeatures: string;
  visualLayout: string;
  search: string;
  languages: string;
  mobile: string;
  aiGenerate: string;
  toc: string;
  whatIs: string;
  stats: string;
  featuredPrompts: string;
  allPrompts: string;
  howToContribute: string;
  license: string;
  acknowledgements: string;
  starHistory: string;
  totalPrompts: string;
  lastUpdated: string;
  metric: string;
  count: string;
  description: string;
  prompt: string;
  generatedImages: string;
  details: string;
  author: string;
  source: string;
  published: string;
  tryItNow: string;
  morePrompts: string;
  morePromptsDesc: string;
  viewAll: string;
  featured: string;
  whatIsIntro: string;
  multimodalUnderstanding: string;
  highQualityGeneration: string;
  fastIteration: string;
  diverseStyles: string;
  preciseControl: string;
  complexScenes: string;
  learnMore: string;
  raycastIntegration: string;
  raycastDescription: string;
  example: string;
  raycastExample: string;
  raycastUsage: string;
  galleryFeature1: string;
  galleryFeature2: string;
  galleryFeature3: string;
  galleryFeature4: string;
  welcomeContributions: string;
  githubIssue: string;
  submitNewPrompt: string;
  fillForm: string;
  submitWait: string;
  approvedSync: string;
  appearInReadme: string;
  note: string;
  noteContent: string;
  seeContributing: string;
  licensedUnder: string;
  autoGenerated: string;
  submitPrompt: string;
  starRepo: string;
  sortedByDate: string;
  handPicked: string;
  githubReadme: string;
  collection: string;
  linearList: string;
  masonryGrid: string;
  ctrlFOnly: string;
  fullTextSearch: string;
  basic: string;
  fullyResponsive: string;
  aiOneClickGen: string;
  categories: string;
  categoryBrowsing: string;
  browseByCategory: string;
}

const en: Translation = {
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "Explore ImagineVid workflows for turning prompt craft into production-ready visuals.",
  subtitle: "A curated collection of Seedream 5 Pro prompts, reusable prompt skills, and visual examples by ImagineVid",
  copyright: "**Copyright Notice**: Prompts are collected or submitted for educational and creative reference with attribution. If any content should be removed, please open an issue and we will handle it promptly.",
  viewInGallery: "View the Curated Collection",
  browseGallery: "Browse the ImagineVid Seedream 5 Pro prompt collection",
  galleryFeatures: "Why use this collection?",
  visualLayout: "Visual Layout",
  search: "Search",
  languages: "Languages",
  mobile: "Mobile",
  aiGenerate: "Prompt Workflow",
  toc: "Table of Contents",
  whatIs: "What is Seedream 5 Pro?",
  stats: "Statistics",
  featuredPrompts: "Featured Prompts",
  allPrompts: "All Prompts",
  howToContribute: "How to Contribute",
  license: "License",
  acknowledgements: "Acknowledgements",
  starHistory: "Star History",
  totalPrompts: "Total Prompts",
  lastUpdated: "Last Updated",
  metric: "Metric",
  count: "Count",
  description: "Description",
  prompt: "Prompt",
  generatedImages: "Generated Images",
  details: "Details",
  author: "Author",
  source: "Source",
  published: "Published",
  tryItNow: "Use this prompt",
  morePrompts: "More Prompts Available",
  morePromptsDesc: "more prompts not shown here",
  viewAll: "View the full generated README set in this repository",
  featured: "Featured",
  whatIsIntro: "**Seedream 5 Pro** is a high-end image generation model family suited for structured creative production:",
  multimodalUnderstanding: "**Prompt Understanding** - Follow detailed scene, style, camera, and layout instructions",
  highQualityGeneration: "**High-Quality Generation** - Produce polished images for editorial, product, and concept work",
  fastIteration: "**Fast Iteration** - Adapt a prompt pattern across many creative directions",
  diverseStyles: "**Diverse Styles** - Support cinematic, commercial, illustration, UI, and poster aesthetics",
  preciseControl: "**Precise Control** - Encode composition, typography, color, lighting, and subject constraints",
  complexScenes: "**Complex Scenes** - Handle multi-object, multi-panel, and workflow-style prompts",
  learnMore: "**Learn More:** follow the source links and examples collected in this repository.",
  raycastIntegration: "Prompt Skill Arguments",
  raycastDescription: "Some prompts support dynamic placeholders using Raycast Snippets-style `{argument ...}` syntax. Look for the Raycast Friendly badge.",
  example: "Example:",
  raycastExample: 'A cinematic poster for "{argument name="product" default="a glass AI camera"}" with {argument name="mood" default="midnight studio lighting"}',
  raycastUsage: "Replace the arguments to reuse the prompt as a compact creative skill.",
  galleryFeature1: "Curated prompt patterns with visual results",
  galleryFeature2: "Source attribution and creator links",
  galleryFeature3: "Multilingual README surfaces",
  galleryFeature4: "Category browsing for repeatable workflows",
  welcomeContributions: "We welcome high-quality prompt submissions through GitHub Issues.",
  githubIssue: "GitHub Issue",
  submitNewPrompt: "Submit New Prompt",
  fillForm: "Fill in the form with prompt details and images",
  submitWait: "Submit and wait for maintainer review",
  approvedSync: "If approved, the issue can be synced into local repository data",
  appearInReadme: "Your prompt will appear after the README generation workflow runs",
  note: "Note:",
  noteContent: "We keep submissions in a structured format so the README stays consistent.",
  seeContributing: "See [CONTRIBUTING.md](docs/CONTRIBUTING.md) for detailed guidelines.",
  licensedUnder: "Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).",
  autoGenerated: "This README is automatically generated. Last updated:",
  submitPrompt: "Submit a Prompt",
  starRepo: "Star this repo",
  sortedByDate: "Sorted by publish date and curation order",
  handPicked: "Hand-picked for reusable structure, visual clarity, and creative range",
  githubReadme: "GitHub README",
  collection: "ImagineVid Collection",
  linearList: "Linear list",
  masonryGrid: "Curated visual sections",
  ctrlFOnly: "Ctrl+F only",
  fullTextSearch: "Structured categories",
  basic: "Basic",
  fullyResponsive: "Readable in every README locale",
  aiOneClickGen: "Reusable prompt skills",
  categories: "Categories",
  categoryBrowsing: "Category browsing",
  browseByCategory: "Browse by Category",
};

const zh: Translation = {
  ...en,
  title: "Seedream 5 Pro 提示词与技能大全",
  relatedPromo: "探索 ImagineVid 工作流，把提示词能力变成可复用的视觉生产方法。",
  subtitle: "由 ImagineVid 整理的 Seedream 5 Pro 提示词、提示词技能与视觉案例集合",
  copyright: "**版权声明**：本仓库内容用于教育与创作参考，并保留来源署名。如需移除任何内容，请提交 issue，我们会及时处理。",
  viewInGallery: "查看精选集合",
  browseGallery: "浏览 ImagineVid Seedream 5 Pro 提示词集合",
  galleryFeatures: "为什么使用这个集合？",
  toc: "目录",
  whatIs: "什么是 Seedream 5 Pro？",
  stats: "统计数据",
  featuredPrompts: "精选提示词",
  allPrompts: "全部提示词",
  howToContribute: "如何贡献",
  totalPrompts: "提示词总数",
  lastUpdated: "最后更新",
  metric: "指标",
  count: "数量",
  description: "描述",
  prompt: "提示词",
  generatedImages: "生成图片",
  details: "详情",
  author: "作者",
  source: "来源",
  published: "发布时间",
  tryItNow: "使用这个提示词",
  featured: "精选",
  whatIsIntro: "**Seedream 5 Pro** 适合高质量图像生成与结构化创意生产：",
  multimodalUnderstanding: "**提示词理解** - 跟随场景、风格、镜头和版式细节",
  highQualityGeneration: "**高质量生成** - 适合海报、产品、概念和编辑视觉",
  fastIteration: "**快速迭代** - 将同一提示词模式扩展到多个方向",
  diverseStyles: "**多样风格** - 支持电影感、商业、插画、UI 和海报美学",
  preciseControl: "**精确控制** - 描述构图、字体、色彩、灯光和主体约束",
  complexScenes: "**复杂场景** - 支持多对象、多分镜和工作流式提示词",
  raycastIntegration: "提示词技能参数",
  raycastDescription: "部分提示词支持 Raycast Snippets 风格的 `{argument ...}` 动态参数。看到 Raycast Friendly 标记即可复用。",
  raycastUsage: "替换参数即可把提示词当成小型创意技能使用。",
  welcomeContributions: "欢迎通过 GitHub Issues 提交高质量提示词。",
  fillForm: "填写提示词、说明和图片信息",
  submitWait: "提交后等待维护者审核",
  approvedSync: "审核通过后可以同步到本地结构化数据",
  appearInReadme: "README 生成流程运行后会展示你的提示词",
  note: "注意：",
  noteContent: "我们用结构化格式维护提交内容，保证 README 展示一致。",
  seeContributing: "详见 [CONTRIBUTING.md](docs/CONTRIBUTING.md)。",
  sortedByDate: "按发布时间和精选顺序排列",
  handPicked: "按可复用结构、视觉清晰度和创意覆盖度精选",
  collection: "ImagineVid 集合",
  masonryGrid: "精选视觉分区",
  fullTextSearch: "结构化分类",
  fullyResponsive: "每个 README 语言版本都可阅读",
  aiOneClickGen: "可复用提示词技能",
  browseByCategory: "按分类浏览",
};

const translations: Record<string, Translation> = {
  en,
  zh,
  "zh-TW": zh,
  "ja-JP": en,
  "ko-KR": en,
  "th-TH": en,
  "vi-VN": en,
  "hi-IN": en,
  "es-ES": en,
  "es-419": en,
  "de-DE": en,
  "fr-FR": en,
  "it-IT": en,
  "pt-BR": en,
  "pt-PT": en,
  "tr-TR": en,
};

export function t(key: keyof Translation, locale = "en"): string {
  return (translations[locale] || en)[key] || en[key];
}
