export interface Translation {
  title: string;
  relatedPromo: string;
  subtitle: string;
  copyright: string;
  viewInGallery: string;
  browseGallery: string;
  galleryFeatures: string;
  feature: string;
  visualLayout: string;
  search: string;
  languages: string;
  mobile: string;
  aiGenerate: string;
  toc: string;
  whatIs: string;
  stats: string;
  featuredPrompts: string;
  allPrompts: string;
  howToContribute: string;
  license: string;
  acknowledgements: string;
  starHistory: string;
  totalPrompts: string;
  lastUpdated: string;
  metric: string;
  count: string;
  description: string;
  prompt: string;
  generatedImages: string;
  details: string;
  author: string;
  source: string;
  published: string;
  tryItNow: string;
  morePrompts: string;
  morePromptsDesc: string;
  viewAll: string;
  featured: string;
  whatIsIntro: string;
  multimodalUnderstanding: string;
  highQualityGeneration: string;
  fastIteration: string;
  diverseStyles: string;
  preciseControl: string;
  complexScenes: string;
  learnMore: string;
  raycastIntegration: string;
  raycastDescription: string;
  example: string;
  raycastExample: string;
  raycastUsage: string;
  galleryFeature1: string;
  galleryFeature2: string;
  galleryFeature3: string;
  galleryFeature4: string;
  welcomeContributions: string;
  githubIssue: string;
  submitNewPrompt: string;
  fillForm: string;
  submitWait: string;
  approvedSync: string;
  appearInReadme: string;
  note: string;
  noteContent: string;
  seeContributing: string;
  licensedUnder: string;
  autoGenerated: string;
  submitPrompt: string;
  starRepo: string;
  sortedByDate: string;
  handPicked: string;
  githubReadme: string;
  collection: string;
  linearList: string;
  masonryGrid: string;
  ctrlFOnly: string;
  fullTextSearch: string;
  basic: string;
  fullyResponsive: string;
  aiOneClickGen: string;
  categories: string;
  categoryBrowsing: string;
  browseByCategory: string;
}

const en: Translation = {
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "Explore ImagineVid workflows for turning prompt craft into production-ready visuals.",
  subtitle: "A curated collection of Seedream 5 Pro prompts, reusable prompt skills, and visual examples by ImagineVid",
  copyright: "**Copyright Notice**: Prompts are collected or submitted for educational and creative reference with attribution. If any content should be removed, please open an issue and we will handle it promptly.",
  viewInGallery: "View the Curated Collection",
  browseGallery: "Browse the ImagineVid Seedream 5 Pro prompt collection",
  galleryFeatures: "Why use this collection?",
  feature: "Feature",
  visualLayout: "Visual Layout",
  search: "Search",
  languages: "Languages",
  mobile: "Mobile",
  aiGenerate: "Prompt Workflow",
  toc: "Table of Contents",
  whatIs: "What is Seedream 5 Pro?",
  stats: "Statistics",
  featuredPrompts: "Featured Prompts",
  allPrompts: "All Prompts",
  howToContribute: "How to Contribute",
  license: "License",
  acknowledgements: "Acknowledgements",
  starHistory: "Star History",
  totalPrompts: "Total Prompts",
  lastUpdated: "Last Updated",
  metric: "Metric",
  count: "Count",
  description: "Description",
  prompt: "Prompt",
  generatedImages: "Generated Images",
  details: "Details",
  author: "Author",
  source: "Source",
  published: "Published",
  tryItNow: "Use this prompt",
  morePrompts: "More Prompts Available",
  morePromptsDesc: "more prompts not shown here",
  viewAll: "View the full generated README set in this repository",
  featured: "Featured",
  whatIsIntro: "**Seedream 5 Pro** is a high-end image generation model family suited for structured creative production:",
  multimodalUnderstanding: "**Prompt Understanding** - Follow detailed scene, style, camera, and layout instructions",
  highQualityGeneration: "**High-Quality Generation** - Produce polished images for editorial, product, and concept work",
  fastIteration: "**Fast Iteration** - Adapt a prompt pattern across many creative directions",
  diverseStyles: "**Diverse Styles** - Support cinematic, commercial, illustration, UI, and poster aesthetics",
  preciseControl: "**Precise Control** - Encode composition, typography, color, lighting, and subject constraints",
  complexScenes: "**Complex Scenes** - Handle multi-object, multi-panel, and workflow-style prompts",
  learnMore: "**Learn More:** follow the source links and examples collected in this repository.",
  raycastIntegration: "Prompt Skill Arguments",
  raycastDescription: "Some prompts support dynamic placeholders using Raycast Snippets-style `{argument ...}` syntax. Look for the Raycast Friendly badge.",
  example: "Example:",
  raycastExample: 'A cinematic poster for "{argument name="product" default="a glass AI camera"}" with {argument name="mood" default="midnight studio lighting"}',
  raycastUsage: "Replace the arguments to reuse the prompt as a compact creative skill.",
  galleryFeature1: "Curated prompt patterns with visual results",
  galleryFeature2: "Source attribution and creator links",
  galleryFeature3: "Multilingual README surfaces",
  galleryFeature4: "Category browsing for repeatable workflows",
  welcomeContributions: "We welcome high-quality prompt submissions through GitHub Issues.",
  githubIssue: "GitHub Issue",
  submitNewPrompt: "Submit New Prompt",
  fillForm: "Fill in the form with prompt details and images",
  submitWait: "Submit and wait for maintainer review",
  approvedSync: "If approved, the issue can be synced into local repository data",
  appearInReadme: "Your prompt will appear after the README generation workflow runs",
  note: "Note:",
  noteContent: "We keep submissions in a structured format so the README stays consistent.",
  seeContributing: "See [CONTRIBUTING.md](docs/CONTRIBUTING.md) for detailed guidelines.",
  licensedUnder: "Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).",
  autoGenerated: "This README is automatically generated. Last updated:",
  submitPrompt: "Submit a Prompt",
  starRepo: "Star this repo",
  sortedByDate: "Sorted by publish date and curation order",
  handPicked: "Hand-picked for reusable structure, visual clarity, and creative range",
  githubReadme: "GitHub README",
  collection: "ImagineVid Collection",
  linearList: "Linear list",
  masonryGrid: "Curated visual sections",
  ctrlFOnly: "Ctrl+F only",
  fullTextSearch: "Structured categories",
  basic: "Basic",
  fullyResponsive: "Readable in every README locale",
  aiOneClickGen: "Reusable prompt skills",
  categories: "Categories",
  categoryBrowsing: "Category browsing",
  browseByCategory: "Browse by Category",
};

const zh: Translation = {
  ...en,
  title: "Seedream 5 Pro 提示词与技能大全",
  relatedPromo: "探索 ImagineVid 工作流，把提示词能力变成可复用的视觉生产方法。",
  subtitle: "由 ImagineVid 整理的 Seedream 5 Pro 提示词、提示词技能与视觉案例集合",
  copyright: "**版权声明**：本仓库内容用于教育与创作参考，并保留来源署名。如需移除任何内容，请提交 issue，我们会及时处理。",
  viewInGallery: "查看精选集合",
  browseGallery: "浏览 ImagineVid Seedream 5 Pro 提示词集合",
  galleryFeatures: "为什么使用这个集合？",
  feature: "功能",
  toc: "目录",
  whatIs: "什么是 Seedream 5 Pro？",
  stats: "统计数据",
  featuredPrompts: "精选提示词",
  allPrompts: "全部提示词",
  howToContribute: "如何贡献",
  totalPrompts: "提示词总数",
  lastUpdated: "最后更新",
  metric: "指标",
  count: "数量",
  description: "描述",
  prompt: "提示词",
  generatedImages: "生成图片",
  details: "详情",
  author: "作者",
  source: "来源",
  published: "发布时间",
  tryItNow: "使用这个提示词",
  featured: "精选",
  whatIsIntro: "**Seedream 5 Pro** 适合高质量图像生成与结构化创意生产：",
  multimodalUnderstanding: "**提示词理解** - 跟随场景、风格、镜头和版式细节",
  highQualityGeneration: "**高质量生成** - 适合海报、产品、概念和编辑视觉",
  fastIteration: "**快速迭代** - 将同一提示词模式扩展到多个方向",
  diverseStyles: "**多样风格** - 支持电影感、商业、插画、UI 和海报美学",
  preciseControl: "**精确控制** - 描述构图、字体、色彩、灯光和主体约束",
  complexScenes: "**复杂场景** - 支持多对象、多分镜和工作流式提示词",
  raycastIntegration: "提示词技能参数",
  raycastDescription: "部分提示词支持 Raycast Snippets 风格的 `{argument ...}` 动态参数。看到 Raycast Friendly 标记即可复用。",
  raycastUsage: "替换参数即可把提示词当成小型创意技能使用。",
  welcomeContributions: "欢迎通过 GitHub Issues 提交高质量提示词。",
  fillForm: "填写提示词、说明和图片信息",
  submitWait: "提交后等待维护者审核",
  approvedSync: "审核通过后可以同步到本地结构化数据",
  appearInReadme: "README 生成流程运行后会展示你的提示词",
  note: "注意：",
  noteContent: "我们用结构化格式维护提交内容，保证 README 展示一致。",
  seeContributing: "详见 [CONTRIBUTING.md](docs/CONTRIBUTING.md)。",
  sortedByDate: "按发布时间和精选顺序排列",
  handPicked: "按可复用结构、视觉清晰度和创意覆盖度精选",
  collection: "ImagineVid 集合",
  masonryGrid: "精选视觉分区",
  fullTextSearch: "结构化分类",
  fullyResponsive: "每个 README 语言版本都可阅读",
  aiOneClickGen: "可复用提示词技能",
  browseByCategory: "按分类浏览",
};

function withEn(overrides: Partial<Translation>): Translation {
  return { ...en, ...overrides };
}

const zhTW = withEn({
  ...zh,
  title: "Seedream 5 Pro 提示詞與技能大全",
  relatedPromo: "探索 ImagineVid 工作流，把提示詞能力變成可重用的視覺生產方法。",
  subtitle: "由 ImagineVid 整理的 Seedream 5 Pro 提示詞、提示詞技能與視覺案例集合",
  copyright: "**版權聲明**：本倉庫內容用於教育與創作參考，並保留來源署名。如需移除任何內容，請提交 issue，我們會及時處理。",
  viewInGallery: "查看精選集合",
  browseGallery: "瀏覽 ImagineVid Seedream 5 Pro 提示詞集合",
  galleryFeatures: "為什麼使用這個集合？",
  feature: "功能",
  toc: "目錄",
  whatIs: "什麼是 Seedream 5 Pro？",
  stats: "統計資料",
  featuredPrompts: "精選提示詞",
  allPrompts: "全部提示詞",
  howToContribute: "如何貢獻",
  totalPrompts: "提示詞總數",
  lastUpdated: "最後更新",
  metric: "指標",
  count: "數量",
  description: "描述",
  prompt: "提示詞",
  generatedImages: "生成圖片",
  details: "詳情",
  author: "作者",
  source: "來源",
  published: "發布時間",
  tryItNow: "使用這個提示詞",
  featured: "精選",
  browseByCategory: "按分類瀏覽",
});

const ja = withEn({
  title: "Awesome Seedream 5 Pro プロンプトとスキル",
  relatedPromo: "ImagineVid のワークフローで、プロンプト設計を制作に使えるビジュアルへ変換します。",
  subtitle: "ImagineVid がキュレーションした Seedream 5 Pro プロンプト、再利用可能なスキル、ビジュアル例",
  copyright: "**著作権について**: 収録内容は教育と創作参考のために出典付きで整理しています。削除依頼は issue でお知らせください。",
  viewInGallery: "キュレーションを見る",
  browseGallery: "ImagineVid Seedream 5 Pro プロンプト集を開く",
  galleryFeatures: "このコレクションの特徴",
  feature: "機能",
  toc: "目次",
  whatIs: "Seedream 5 Pro とは？",
  stats: "統計",
  featuredPrompts: "注目プロンプト",
  allPrompts: "すべてのプロンプト",
  howToContribute: "貢献方法",
  totalPrompts: "プロンプト総数",
  lastUpdated: "最終更新",
  metric: "項目",
  count: "数",
  description: "説明",
  prompt: "プロンプト",
  generatedImages: "生成画像",
  details: "詳細",
  author: "作者",
  source: "出典",
  published: "公開日",
  tryItNow: "このプロンプトを使う",
  featured: "注目",
  browseByCategory: "カテゴリ別に見る",
});

const ko = withEn({
  title: "Awesome Seedream 5 Pro 프롬프트와 스킬",
  relatedPromo: "ImagineVid 워크플로로 프롬프트 아이디어를 제작 가능한 비주얼로 바꿉니다.",
  subtitle: "ImagineVid가 큐레이션한 Seedream 5 Pro 프롬프트, 재사용 가능한 스킬, 시각 예시 모음",
  copyright: "**저작권 안내**: 이 콘텐츠는 교육 및 창작 참고용으로 출처와 함께 정리했습니다. 삭제가 필요하면 issue를 열어 주세요.",
  viewInGallery: "큐레이션 보기",
  browseGallery: "ImagineVid Seedream 5 Pro 프롬프트 컬렉션 보기",
  galleryFeatures: "이 컬렉션을 쓰는 이유",
  feature: "기능",
  toc: "목차",
  whatIs: "Seedream 5 Pro란?",
  stats: "통계",
  featuredPrompts: "추천 프롬프트",
  allPrompts: "전체 프롬프트",
  howToContribute: "기여 방법",
  totalPrompts: "총 프롬프트",
  lastUpdated: "마지막 업데이트",
  metric: "항목",
  count: "수량",
  description: "설명",
  prompt: "프롬프트",
  generatedImages: "생성 이미지",
  details: "세부 정보",
  author: "작성자",
  source: "출처",
  published: "게시일",
  tryItNow: "이 프롬프트 사용",
  featured: "추천",
  browseByCategory: "카테고리별 보기",
});

const es = withEn({
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "Explora flujos de ImagineVid para convertir prompts en visuales listos para producción.",
  subtitle: "Una colección curada por ImagineVid de prompts, habilidades reutilizables y ejemplos visuales para Seedream 5 Pro",
  copyright: "**Aviso de copyright**: Los prompts se recopilan con atribución para referencia educativa y creativa. Abre un issue si algo debe retirarse.",
  viewInGallery: "Ver la colección curada",
  browseGallery: "Explorar la colección de prompts de ImagineVid Seedream 5 Pro",
  galleryFeatures: "Por qué usar esta colección",
  feature: "Función",
  toc: "Índice",
  whatIs: "¿Qué es Seedream 5 Pro?",
  stats: "Estadísticas",
  featuredPrompts: "Prompts destacados",
  allPrompts: "Todos los prompts",
  howToContribute: "Cómo contribuir",
  totalPrompts: "Prompts totales",
  lastUpdated: "Última actualización",
  metric: "Métrica",
  count: "Cantidad",
  description: "Descripción",
  prompt: "Prompt",
  generatedImages: "Imágenes generadas",
  details: "Detalles",
  author: "Autor",
  source: "Fuente",
  published: "Publicado",
  tryItNow: "Usar este prompt",
  featured: "Destacado",
  browseByCategory: "Explorar por categoría",
});

const de = withEn({
  title: "Awesome Seedream 5 Pro Prompts und Skills",
  relatedPromo: "Entdecke ImagineVid-Workflows, die Prompt-Handwerk in produktionsreife Visuals verwandeln.",
  subtitle: "Eine von ImagineVid kuratierte Sammlung von Seedream 5 Pro Prompts, wiederverwendbaren Skills und visuellen Beispielen",
  viewInGallery: "Kuratierte Sammlung ansehen",
  browseGallery: "ImagineVid Seedream 5 Pro Prompt-Sammlung öffnen",
  galleryFeatures: "Warum diese Sammlung nutzen?",
  feature: "Funktion",
  toc: "Inhalt",
  whatIs: "Was ist Seedream 5 Pro?",
  stats: "Statistiken",
  featuredPrompts: "Ausgewählte Prompts",
  allPrompts: "Alle Prompts",
  howToContribute: "Mitwirken",
  totalPrompts: "Prompts gesamt",
  lastUpdated: "Zuletzt aktualisiert",
  metric: "Metrik",
  count: "Anzahl",
  description: "Beschreibung",
  prompt: "Prompt",
  generatedImages: "Generierte Bilder",
  details: "Details",
  author: "Autor",
  source: "Quelle",
  published: "Veröffentlicht",
  tryItNow: "Diesen Prompt nutzen",
  featured: "Ausgewählt",
  browseByCategory: "Nach Kategorie durchsuchen",
});

const fr = withEn({
  title: "Awesome Seedream 5 Pro Prompts et Skills",
  relatedPromo: "Explorez les workflows ImagineVid pour transformer l’art du prompt en visuels prêts pour la production.",
  subtitle: "Une collection ImagineVid de prompts Seedream 5 Pro, de skills réutilisables et d’exemples visuels",
  viewInGallery: "Voir la collection",
  browseGallery: "Parcourir la collection ImagineVid Seedream 5 Pro",
  galleryFeatures: "Pourquoi utiliser cette collection ?",
  feature: "Fonction",
  toc: "Sommaire",
  whatIs: "Qu’est-ce que Seedream 5 Pro ?",
  stats: "Statistiques",
  featuredPrompts: "Prompts en vedette",
  allPrompts: "Tous les prompts",
  howToContribute: "Contribuer",
  totalPrompts: "Total des prompts",
  lastUpdated: "Dernière mise à jour",
  metric: "Métrique",
  count: "Nombre",
  description: "Description",
  prompt: "Prompt",
  generatedImages: "Images générées",
  details: "Détails",
  author: "Auteur",
  source: "Source",
  published: "Publié",
  tryItNow: "Utiliser ce prompt",
  featured: "En vedette",
  browseByCategory: "Parcourir par catégorie",
});

const it = withEn({
  title: "Awesome Seedream 5 Pro Prompts e Skills",
  relatedPromo: "Esplora i workflow ImagineVid per trasformare i prompt in visual pronti per la produzione.",
  subtitle: "Una raccolta ImagineVid di prompt Seedream 5 Pro, skill riutilizzabili ed esempi visivi",
  viewInGallery: "Vedi la collezione",
  browseGallery: "Sfoglia la raccolta ImagineVid Seedream 5 Pro",
  galleryFeatures: "Perché usare questa raccolta?",
  feature: "Funzione",
  toc: "Indice",
  whatIs: "Che cos’è Seedream 5 Pro?",
  stats: "Statistiche",
  featuredPrompts: "Prompt in evidenza",
  allPrompts: "Tutti i prompt",
  howToContribute: "Come contribuire",
  totalPrompts: "Prompt totali",
  lastUpdated: "Ultimo aggiornamento",
  metric: "Metrica",
  count: "Conteggio",
  description: "Descrizione",
  generatedImages: "Immagini generate",
  details: "Dettagli",
  author: "Autore",
  source: "Fonte",
  published: "Pubblicato",
  tryItNow: "Usa questo prompt",
  featured: "In evidenza",
  browseByCategory: "Sfoglia per categoria",
});

const ptBR = withEn({
  title: "Awesome Seedream 5 Pro Prompts e Skills",
  relatedPromo: "Explore fluxos da ImagineVid para transformar prompts em visuais prontos para produção.",
  subtitle: "Uma coleção da ImagineVid com prompts, habilidades reutilizáveis e exemplos visuais para Seedream 5 Pro",
  viewInGallery: "Ver a coleção",
  browseGallery: "Explorar a coleção ImagineVid Seedream 5 Pro",
  galleryFeatures: "Por que usar esta coleção?",
  feature: "Recurso",
  toc: "Sumário",
  whatIs: "O que é Seedream 5 Pro?",
  stats: "Estatísticas",
  featuredPrompts: "Prompts em destaque",
  allPrompts: "Todos os prompts",
  howToContribute: "Como contribuir",
  totalPrompts: "Total de prompts",
  lastUpdated: "Última atualização",
  metric: "Métrica",
  count: "Quantidade",
  description: "Descrição",
  generatedImages: "Imagens geradas",
  details: "Detalhes",
  author: "Autor",
  source: "Fonte",
  published: "Publicado",
  tryItNow: "Usar este prompt",
  featured: "Destaque",
  browseByCategory: "Explorar por categoria",
});

const ptPT = withEn({
  ...ptBR,
  relatedPromo: "Explore fluxos da ImagineVid para transformar prompts em visuais prontos para produção.",
  browseGallery: "Explorar a coleção ImagineVid Seedream 5 Pro",
});

const tr = withEn({
  title: "Awesome Seedream 5 Pro Promptları ve Becerileri",
  relatedPromo: "Prompt bilgisini üretime hazır görsellere dönüştüren ImagineVid iş akışlarını keşfedin.",
  subtitle: "ImagineVid tarafından seçilmiş Seedream 5 Pro promptları, yeniden kullanılabilir beceriler ve görsel örnekler",
  viewInGallery: "Seçilmiş koleksiyonu görüntüle",
  browseGallery: "ImagineVid Seedream 5 Pro prompt koleksiyonunu aç",
  galleryFeatures: "Bu koleksiyon neden kullanılır?",
  feature: "Özellik",
  toc: "İçindekiler",
  whatIs: "Seedream 5 Pro nedir?",
  stats: "İstatistikler",
  featuredPrompts: "Öne çıkan promptlar",
  allPrompts: "Tüm promptlar",
  howToContribute: "Nasıl katkı verilir",
  totalPrompts: "Toplam prompt",
  lastUpdated: "Son güncelleme",
  metric: "Metrik",
  count: "Sayı",
  description: "Açıklama",
  prompt: "Prompt",
  generatedImages: "Üretilen görseller",
  details: "Detaylar",
  author: "Yazar",
  source: "Kaynak",
  published: "Yayınlandı",
  tryItNow: "Bu promptu kullan",
  featured: "Öne çıkan",
  browseByCategory: "Kategoriye göre gez",
});

const vi = withEn({
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "Khám phá workflow ImagineVid để biến kỹ thuật prompt thành hình ảnh sẵn sàng sản xuất.",
  subtitle: "Bộ sưu tập ImagineVid gồm prompt Seedream 5 Pro, kỹ năng tái sử dụng và ví dụ hình ảnh",
  viewInGallery: "Xem bộ sưu tập",
  browseGallery: "Duyệt bộ sưu tập prompt ImagineVid Seedream 5 Pro",
  galleryFeatures: "Vì sao dùng bộ sưu tập này?",
  feature: "Tính năng",
  toc: "Mục lục",
  whatIs: "Seedream 5 Pro là gì?",
  stats: "Thống kê",
  featuredPrompts: "Prompt nổi bật",
  allPrompts: "Tất cả prompt",
  howToContribute: "Cách đóng góp",
  totalPrompts: "Tổng số prompt",
  lastUpdated: "Cập nhật lần cuối",
  metric: "Chỉ số",
  count: "Số lượng",
  description: "Mô tả",
  generatedImages: "Ảnh đã tạo",
  details: "Chi tiết",
  author: "Tác giả",
  source: "Nguồn",
  published: "Đã đăng",
  tryItNow: "Dùng prompt này",
  featured: "Nổi bật",
  browseByCategory: "Duyệt theo danh mục",
});

const th = withEn({
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "สำรวจเวิร์กโฟลว์ ImagineVid เพื่อเปลี่ยน prompt ให้เป็นภาพพร้อมใช้งานจริง",
  subtitle: "คอลเลกชัน prompt, skill ที่ใช้ซ้ำได้ และตัวอย่างภาพสำหรับ Seedream 5 Pro โดย ImagineVid",
  viewInGallery: "ดูคอลเลกชัน",
  browseGallery: "เปิดคอลเลกชัน prompt ของ ImagineVid Seedream 5 Pro",
  galleryFeatures: "เหตุผลที่ควรใช้คอลเลกชันนี้",
  feature: "ฟีเจอร์",
  toc: "สารบัญ",
  whatIs: "Seedream 5 Pro คืออะไร?",
  stats: "สถิติ",
  featuredPrompts: "Prompt แนะนำ",
  allPrompts: "Prompt ทั้งหมด",
  howToContribute: "วิธีร่วมสนับสนุน",
  totalPrompts: "จำนวน prompt ทั้งหมด",
  lastUpdated: "อัปเดตล่าสุด",
  metric: "ตัวชี้วัด",
  count: "จำนวน",
  description: "คำอธิบาย",
  prompt: "Prompt",
  generatedImages: "ภาพที่สร้าง",
  details: "รายละเอียด",
  author: "ผู้เขียน",
  source: "แหล่งที่มา",
  published: "เผยแพร่",
  tryItNow: "ใช้ prompt นี้",
  featured: "แนะนำ",
  browseByCategory: "ดูตามหมวดหมู่",
});

const hi = withEn({
  title: "Awesome Seedream 5 Pro Prompts and Skills",
  relatedPromo: "ImagineVid workflows देखें जो prompt craft को production-ready visuals में बदलते हैं.",
  subtitle: "ImagineVid द्वारा चुने गए Seedream 5 Pro prompts, reusable skills और visual examples",
  viewInGallery: "चुना हुआ संग्रह देखें",
  browseGallery: "ImagineVid Seedream 5 Pro prompt collection खोलें",
  galleryFeatures: "इस collection का उपयोग क्यों करें?",
  feature: "Feature",
  toc: "विषय सूची",
  whatIs: "Seedream 5 Pro क्या है?",
  stats: "आंकड़े",
  featuredPrompts: "Featured prompts",
  allPrompts: "सभी prompts",
  howToContribute: "योगदान कैसे करें",
  totalPrompts: "कुल prompts",
  lastUpdated: "अंतिम अपडेट",
  metric: "Metric",
  count: "Count",
  description: "विवरण",
  generatedImages: "Generated images",
  details: "Details",
  author: "Author",
  source: "Source",
  published: "Published",
  tryItNow: "यह prompt उपयोग करें",
  featured: "Featured",
  browseByCategory: "Category से browse करें",
});

const translations: Record<string, Translation> = {
  en,
  zh,
  "zh-TW": zhTW,
  "ja-JP": ja,
  "ko-KR": ko,
  "th-TH": th,
  "vi-VN": vi,
  "hi-IN": hi,
  "es-ES": es,
  "es-419": es,
  "de-DE": de,
  "fr-FR": fr,
  "it-IT": it,
  "pt-BR": ptBR,
  "pt-PT": ptPT,
  "tr-TR": tr,
};

export function t(key: keyof Translation, locale = "en"): string {
  return (translations[locale] || en)[key] || en[key];
}
